###
GET http://localhost:4000/ping
###
GET http://localhost:4000/eventos
###
GET http://localhost:4000/eventos/1f867156-08cb-4b5e-8907-804edea59e0b
###
GET http://localhost:4000/eventos/evento-fullstack
###
GET http://localhost:4000/eventos/validar/evento-fullstack/1f867156-08cb-4b5e-8907-804edea59e0b
###
POST http://localhost:4000/eventos/acessar
Content-Type: application/json

{
  "id": "1f867156-08cb-4b5e-8907-804edea59e0b",
  "senha": "senha123"
}
###
POST http://localhost:4000/eventos/evento-fullstack/convidado
Content-Type: application/json

{
  "id": "ecd2eb93-c8b4-4ad2-9171-f282c71c8a66",
  "nome": "Regina Maciel",
  "email": "reginamaciel.contato@gmail.com.br",
  "confirmado": true,
  "possuiAcompanhantes": false,
  "qtdeAcompanhantes": 0  
}